# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_add_subnetwork_v1.proto

require 'google/protobuf'

require 'blockchain_token_type_v1_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_add_subnetwork_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_add_subnetwork_v1" do
      optional :token_type, :enum, 1, "helium.blockchain_token_type_v1"
      optional :subnetwork_key, :bytes, 2
      repeated :reward_server_keys, :bytes, 3
      optional :premine, :uint64, 4
      optional :network_signature, :bytes, 5
      optional :subnetwork_signature, :bytes, 6
    end
  end
end

module Helium
  Blockchain_txn_add_subnetwork_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_add_subnetwork_v1").msgclass
end
