# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_rewards_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_rewards_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_reward_v1" do
      optional :account, :bytes, 1
      optional :gateway, :bytes, 3
      optional :amount, :uint64, 4
      optional :type, :enum, 5, "helium.blockchain_txn_reward_v1.Type"
    end
    add_enum "helium.blockchain_txn_reward_v1.Type" do
      value :securities, 0
      value :data_credits, 1
      value :poc_challengees, 2
      value :poc_challengers, 3
      value :poc_witnesses, 4
      value :consensus, 5
    end
    add_message "helium.blockchain_txn_rewards_v1" do
      optional :start_epoch, :uint64, 1
      optional :end_epoch, :uint64, 2
      repeated :rewards, :message, 3, "helium.blockchain_txn_reward_v1"
    end
  end
end

module Helium
  Blockchain_txn_reward_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_reward_v1").msgclass
  Blockchain_txn_reward_v1::Type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_reward_v1.Type").enummodule
  Blockchain_txn_rewards_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_rewards_v1").msgclass
end
