# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_validator_heartbeat_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_validator_heartbeat_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_validator_heartbeat_v1" do
      optional :address, :bytes, 1
      optional :height, :uint64, 2
      optional :version, :uint32, 3
      optional :signature, :bytes, 4
      repeated :poc_key_proposals, :bytes, 5
      repeated :reactivated_gws, :bytes, 6
    end
  end
end

module Helium
  Blockchain_txn_validator_heartbeat_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_validator_heartbeat_v1").msgclass
end
