# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_transfer_hotspot_v2.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_transfer_hotspot_v2.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_transfer_hotspot_v2" do
      optional :gateway, :bytes, 1
      optional :owner, :bytes, 2
      optional :owner_signature, :bytes, 3
      optional :new_owner, :bytes, 4
      optional :fee, :uint64, 5
      optional :nonce, :uint64, 6
    end
  end
end

module Helium
  Blockchain_txn_transfer_hotspot_v2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_transfer_hotspot_v2").msgclass
end
