# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_poc_core_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_poc_core_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_poc_receipt_v1" do
      optional :gateway, :bytes, 1
      optional :timestamp, :uint64, 2
      optional :signal, :sint32, 3
      optional :data, :bytes, 4
      optional :origin, :enum, 5, "helium.origin"
      optional :signature, :bytes, 6
      optional :snr, :float, 7
      optional :frequency, :float, 8
      optional :channel, :int32, 9
      optional :datarate, :string, 10
      optional :addr_hash, :bytes, 11
      optional :tx_power, :int32, 12
    end
    add_message "helium.blockchain_poc_witness_v1" do
      optional :gateway, :bytes, 1
      optional :timestamp, :uint64, 2
      optional :signal, :sint32, 3
      optional :packet_hash, :bytes, 4
      optional :signature, :bytes, 5
      optional :snr, :float, 6
      optional :frequency, :float, 7
      optional :channel, :int32, 8
      optional :datarate, :string, 9
    end
    add_message "helium.blockchain_poc_response_v1" do
      oneof :payload do
        optional :receipt, :message, 1, "helium.blockchain_poc_receipt_v1"
        optional :witness, :message, 2, "helium.blockchain_poc_witness_v1"
      end
    end
    add_message "helium.blockchain_poc_path_element_v1" do
      optional :challengee, :bytes, 1
      optional :receipt, :message, 2, "helium.blockchain_poc_receipt_v1"
      repeated :witnesses, :message, 3, "helium.blockchain_poc_witness_v1"
    end
    add_enum "helium.origin" do
      value :p2p, 0
      value :radio, 1
    end
  end
end

module Helium
  Blockchain_poc_receipt_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_poc_receipt_v1").msgclass
  Blockchain_poc_witness_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_poc_witness_v1").msgclass
  Blockchain_poc_response_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_poc_response_v1").msgclass
  Blockchain_poc_path_element_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_poc_path_element_v1").msgclass
  Origin = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.origin").enummodule
end
