# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_assert_location_v2.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_assert_location_v2.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_assert_location_v2" do
      optional :gateway, :bytes, 1
      optional :owner, :bytes, 2
      optional :payer, :bytes, 3
      optional :owner_signature, :bytes, 4
      optional :payer_signature, :bytes, 5
      optional :location, :string, 6
      optional :nonce, :uint64, 7
      optional :gain, :int32, 8
      optional :elevation, :int32, 9
      optional :staking_fee, :uint64, 10
      optional :fee, :uint64, 11
    end
  end
end

module Helium
  Blockchain_txn_assert_location_v2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_assert_location_v2").msgclass
end
