# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_state_channel_open_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_state_channel_open_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_state_channel_open_v1" do
      optional :id, :bytes, 1
      optional :owner, :bytes, 2
      optional :amount, :int64, 3
      optional :expire_within, :int64, 4
      optional :oui, :uint64, 5
      optional :nonce, :uint64, 6
      optional :signature, :bytes, 7
      optional :fee, :uint64, 8
    end
  end
end

module Helium
  Blockchain_txn_state_channel_open_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_state_channel_open_v1").msgclass
end
