# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_create_htlc_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_create_htlc_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_create_htlc_v1" do
      optional :payer, :bytes, 1
      optional :payee, :bytes, 2
      optional :address, :bytes, 3
      optional :hashlock, :bytes, 4
      optional :timelock, :uint64, 5
      optional :amount, :uint64, 6
      optional :fee, :uint64, 7
      optional :signature, :bytes, 8
      optional :nonce, :uint64, 9
    end
  end
end

module Helium
  Blockchain_txn_create_htlc_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_create_htlc_v1").msgclass
end
