# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_transfer_validator_stake_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_transfer_validator_stake_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_transfer_validator_stake_v1" do
      optional :old_address, :bytes, 1
      optional :new_address, :bytes, 2
      optional :old_owner, :bytes, 3
      optional :new_owner, :bytes, 4
      optional :old_owner_signature, :bytes, 5
      optional :new_owner_signature, :bytes, 6
      optional :fee, :uint64, 7
      optional :stake_amount, :uint64, 8
      optional :payment_amount, :uint64, 9
    end
  end
end

module Helium
  Blockchain_txn_transfer_validator_stake_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_transfer_validator_stake_v1").msgclass
end
