# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_state_channel_v1.proto

require 'google/protobuf'

require 'packet_pb'
require 'skewed_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_state_channel_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_state_channel_summary_v1" do
      optional :client_pubkeybin, :bytes, 1
      optional :num_packets, :uint64, 2
      optional :num_dcs, :uint64, 3
    end
    add_message "helium.blockchain_state_channel_v1" do
      optional :id, :bytes, 1
      optional :owner, :bytes, 2
      optional :credits, :uint64, 3
      optional :nonce, :uint64, 4
      repeated :summaries, :message, 5, "helium.blockchain_state_channel_summary_v1"
      optional :root_hash, :bytes, 6
      optional :skewed, :message, 7, "helium.skewed"
      optional :state, :enum, 8, "helium.blockchain_state_channel_state_v1"
      optional :expire_at_block, :uint64, 9
      optional :signature, :bytes, 10
    end
    add_message "helium.blockchain_state_channel_response_v1" do
      optional :accepted, :bool, 1
      optional :downlink, :message, 4, "helium.packet"
    end
    add_message "helium.blockchain_state_channel_packet_v1" do
      optional :packet, :message, 1, "helium.packet"
      optional :hotspot, :bytes, 2
      optional :signature, :bytes, 3
      optional :region, :enum, 4, "helium.blockchain_state_channel_packet_v1.Region"
    end
    add_enum "helium.blockchain_state_channel_packet_v1.Region" do
      value :US915, 0
      value :EU868, 1
      value :EU433, 2
      value :CN470, 3
      value :CN779, 4
      value :AU915, 5
      value :AS923, 6
      value :KR920, 7
      value :IN865, 8
    end
    add_message "helium.blockchain_state_channel_message_v1" do
      oneof :msg do
        optional :response, :message, 2, "helium.blockchain_state_channel_response_v1"
        optional :packet, :message, 4, "helium.blockchain_state_channel_packet_v1"
      end
    end
    add_enum "helium.blockchain_state_channel_state_v1" do
      value :open, 0
      value :closed, 1
    end
  end
end

module Helium
  Blockchain_state_channel_summary_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_state_channel_summary_v1").msgclass
  Blockchain_state_channel_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_state_channel_v1").msgclass
  Blockchain_state_channel_response_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_state_channel_response_v1").msgclass
  Blockchain_state_channel_packet_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_state_channel_packet_v1").msgclass
  Blockchain_state_channel_packet_v1::Region = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_state_channel_packet_v1.Region").enummodule
  Blockchain_state_channel_message_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_state_channel_message_v1").msgclass
  Blockchain_state_channel_state_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_state_channel_state_v1").enummodule
end
