# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_token_type_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_token_type_v1.proto", :syntax => :proto3) do
    add_enum "helium.blockchain_token_type_v1" do
      value :hnt, 0
      value :hst, 1
      value :mobile, 2
      value :iot, 3
    end
  end
end

module Helium
  Blockchain_token_type_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_token_type_v1").enummodule
end
