# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_oui_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_oui_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_oui_v1" do
      optional :owner, :bytes, 1
      repeated :addresses, :bytes, 2
      optional :filter, :bytes, 3
      optional :requested_subnet_size, :uint32, 4
      optional :payer, :bytes, 5
      optional :staking_fee, :uint64, 6
      optional :fee, :uint64, 7
      optional :owner_signature, :bytes, 8
      optional :payer_signature, :bytes, 9
      optional :oui, :uint64, 10
    end
  end
end

module Helium
  Blockchain_txn_oui_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_oui_v1").msgclass
end
