# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_handler.proto

require 'google/protobuf'

require 'blockchain_txn_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_handler.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_request_v1" do
      optional :type, :enum, 1, "helium.request_type"
      optional :key, :bytes, 2
      optional :txn, :message, 3, "helium.blockchain_txn"
    end
    add_message "helium.blockchain_txn_info_v1" do
      optional :result, :bytes, 1
      optional :details, :bytes, 2
      optional :trace, :bytes, 3
      optional :height, :uint64, 4
      optional :queue_pos, :uint32, 5
      optional :queue_len, :uint32, 6
      optional :txn_protocol_version, :uint32, 7
    end
    add_enum "helium.request_type" do
      value :submit, 0
      value :update, 1
    end
  end
end

module Helium
  Blockchain_txn_request_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_request_v1").msgclass
  Blockchain_txn_info_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_info_v1").msgclass
  Request_type = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.request_type").enummodule
end
