# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_payment_v2.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_payment_v2.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_payment_v2" do
      optional :payer, :bytes, 1
      repeated :payments, :message, 2, "helium.payment"
      optional :fee, :uint64, 3
      optional :nonce, :uint64, 4
      optional :signature, :bytes, 5
    end
    add_message "helium.payment" do
      optional :payee, :bytes, 1
      optional :amount, :uint64, 2
    end
  end
end

module Helium
  Blockchain_txn_payment_v2 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_payment_v2").msgclass
  Payment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.payment").msgclass
end
