# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_update_subnetwork_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_update_subnetwork_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_update_subnetwork_v1" do
      optional :subnetwork_key, :bytes, 1
      optional :network_signature, :bytes, 2
      repeated :reward_server_keys, :bytes, 3
      optional :subnetwork_signature, :bytes, 4
      optional :nonce, :uint64, 5
    end
  end
end

module Helium
  Blockchain_txn_update_subnetwork_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_update_subnetwork_v1").msgclass
end
