# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: blockchain_txn_consensus_group_v1.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("blockchain_txn_consensus_group_v1.proto", :syntax => :proto3) do
    add_message "helium.blockchain_txn_consensus_group_v1" do
      repeated :members, :bytes, 1
      optional :proof, :bytes, 2
      optional :height, :uint64, 3
      optional :delay, :uint32, 4
    end
  end
end

module Helium
  Blockchain_txn_consensus_group_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.blockchain_txn_consensus_group_v1").msgclass
end
