# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: region.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("region.proto", :syntax => :proto3) do
    add_enum "helium.region" do
      value :US915, 0
      value :EU868, 1
      value :EU433, 2
      value :CN470, 3
      value :CN779, 4
      value :AU915, 5
      value :AS923_1, 6
      value :KR920, 7
      value :IN865, 8
      value :AS923_2, 9
      value :AS923_3, 10
      value :AS923_4, 11
      value :AS923_1B, 12
      value :CD900_1A, 13
      value :RU864, 14
      value :EU868_A, 15
      value :EU868_B, 16
      value :EU868_C, 17
      value :EU868_D, 18
      value :EU868_E, 19
      value :EU868_F, 20
      value :AU915_SB1, 21
      value :AU915_SB2, 22
      value :AS923_1A, 23
      value :AS923_1C, 24
      value :AS923_1D, 25
      value :AS923_1E, 26
      value :AS923_1F, 27
    end
  end
end

module Helium
  Region = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.region").enummodule
end
