# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/downlink.proto

require 'google/protobuf'

require 'region_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/downlink.proto", :syntax => :proto3) do
    add_message "helium.downlink.http_roaming_register_v1" do
      optional :region, :enum, 1, "helium.region"
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.downlink.http_roaming_downlink_v1" do
      optional :data, :bytes, 1
    end
  end
end

module Helium
  module Downlink
    Http_roaming_register_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.downlink.http_roaming_register_v1").msgclass
    Http_roaming_downlink_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.downlink.http_roaming_downlink_v1").msgclass
  end
end
