# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/follower.proto

require 'google/protobuf'

require 'blockchain_txn_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/follower.proto", :syntax => :proto3) do
    add_message "helium.follower_txn_stream_req_v1" do
      proto3_optional :height, :uint64, 1
      optional :txn_hash, :bytes, 2
      repeated :txn_types, :string, 3
    end
    add_message "helium.follower_txn_stream_resp_v1" do
      optional :height, :uint64, 1
      optional :txn_hash, :bytes, 2
      optional :txn, :message, 3, "helium.blockchain_txn"
      optional :timestamp, :uint64, 4
    end
    add_message "helium.follower_gateway_req_v1" do
      optional :address, :bytes, 1
    end
    add_message "helium.follower_gateway_resp_v1" do
      optional :height, :uint64, 1
      optional :location, :string, 2
      optional :address, :bytes, 3
      optional :owner, :bytes, 4
    end
  end
end

module Helium
  Follower_txn_stream_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.follower_txn_stream_req_v1").msgclass
  Follower_txn_stream_resp_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.follower_txn_stream_resp_v1").msgclass
  Follower_gateway_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.follower_gateway_req_v1").msgclass
  Follower_gateway_resp_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.follower_gateway_resp_v1").msgclass
end
