# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/iot_config.proto

require 'google/protobuf'

require 'blockchain_region_param_v1_pb'
require 'region_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/iot_config.proto", :syntax => :proto3) do
    add_message "helium.iot_config.org_v1" do
      optional :oui, :uint64, 1
      optional :owner, :bytes, 2
      optional :payer, :bytes, 3
      repeated :delegate_keys, :bytes, 4
      optional :locked, :bool, 5
    end
    add_message "helium.iot_config.devaddr_range_v1" do
      optional :route_id, :string, 1
      optional :start_addr, :uint32, 2
      optional :end_addr, :uint32, 3
    end
    add_message "helium.iot_config.devaddr_constraint_v1" do
      optional :start_addr, :uint32, 1
      optional :end_addr, :uint32, 2
    end
    add_message "helium.iot_config.eui_pair_v1" do
      optional :route_id, :string, 1
      optional :app_eui, :uint64, 2
      optional :dev_eui, :uint64, 3
    end
    add_message "helium.iot_config.protocol_packet_router_v1" do
    end
    add_message "helium.iot_config.protocol_gwmp_mapping_v1" do
      optional :region, :enum, 1, "helium.region"
      optional :port, :uint32, 2
    end
    add_message "helium.iot_config.protocol_gwmp_v1" do
      repeated :mapping, :message, 1, "helium.iot_config.protocol_gwmp_mapping_v1"
    end
    add_message "helium.iot_config.protocol_http_roaming_v1" do
      optional :flow_type, :enum, 1, "helium.iot_config.protocol_http_roaming_v1.flow_type_v1"
      optional :dedupe_timeout, :uint32, 2
      optional :path, :string, 3
      optional :auth_header, :string, 4
    end
    add_enum "helium.iot_config.protocol_http_roaming_v1.flow_type_v1" do
      value :sync, 0
      value :async, 1
    end
    add_message "helium.iot_config.server_v1" do
      optional :host, :string, 1
      optional :port, :uint32, 2
      oneof :protocol do
        optional :packet_router, :message, 3, "helium.iot_config.protocol_packet_router_v1"
        optional :gwmp, :message, 4, "helium.iot_config.protocol_gwmp_v1"
        optional :http_roaming, :message, 5, "helium.iot_config.protocol_http_roaming_v1"
      end
    end
    add_message "helium.iot_config.route_v1" do
      optional :id, :string, 1
      optional :net_id, :uint32, 2
      optional :oui, :uint64, 3
      optional :server, :message, 4, "helium.iot_config.server_v1"
      optional :max_copies, :uint32, 5
      optional :active, :bool, 6
      optional :locked, :bool, 7
    end
    add_message "helium.iot_config.org_list_req_v1" do
    end
    add_message "helium.iot_config.org_list_res_v1" do
      repeated :orgs, :message, 1, "helium.iot_config.org_v1"
    end
    add_message "helium.iot_config.org_get_req_v1" do
      optional :oui, :uint64, 1
    end
    add_message "helium.iot_config.org_create_helium_req_v1" do
      optional :owner, :bytes, 1
      optional :payer, :bytes, 2
      optional :devaddrs, :uint64, 3
      optional :timestamp, :uint64, 4
      optional :signature, :bytes, 5
      repeated :delegate_keys, :bytes, 6
    end
    add_message "helium.iot_config.org_create_roamer_req_v1" do
      optional :owner, :bytes, 1
      optional :payer, :bytes, 2
      optional :net_id, :uint32, 3
      optional :timestamp, :uint64, 4
      optional :signature, :bytes, 5
      repeated :delegate_keys, :bytes, 6
    end
    add_message "helium.iot_config.org_res_v1" do
      optional :org, :message, 1, "helium.iot_config.org_v1"
      optional :net_id, :uint32, 2
      repeated :devaddr_constraints, :message, 3, "helium.iot_config.devaddr_constraint_v1"
    end
    add_message "helium.iot_config.org_disable_req_v1" do
      optional :oui, :uint64, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.org_disable_res_v1" do
      optional :oui, :uint64, 1
    end
    add_message "helium.iot_config.org_enable_req_v1" do
      optional :oui, :uint64, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.org_enable_res_v1" do
      optional :oui, :uint64, 1
    end
    add_message "helium.iot_config.route_list_req_v1" do
      optional :oui, :uint64, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.route_list_res_v1" do
      repeated :routes, :message, 1, "helium.iot_config.route_v1"
    end
    add_message "helium.iot_config.route_get_req_v1" do
      optional :id, :string, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.route_create_req_v1" do
      optional :oui, :uint64, 1
      optional :route, :message, 2, "helium.iot_config.route_v1"
      optional :timestamp, :uint64, 3
      optional :signature, :bytes, 4
    end
    add_message "helium.iot_config.route_update_req_v1" do
      optional :route, :message, 1, "helium.iot_config.route_v1"
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.route_delete_req_v1" do
      optional :id, :string, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.route_get_euis_req_v1" do
      optional :route_id, :string, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.route_update_euis_req_v1" do
      optional :action, :enum, 1, "helium.iot_config.action_v1"
      optional :eui_pair, :message, 2, "helium.iot_config.eui_pair_v1"
      optional :timestamp, :uint64, 3
      optional :signature, :bytes, 4
    end
    add_message "helium.iot_config.route_euis_res_v1" do
    end
    add_message "helium.iot_config.route_get_devaddr_ranges_req_v1" do
      optional :route_id, :string, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.route_update_devaddr_ranges_req_v1" do
      optional :action, :enum, 1, "helium.iot_config.action_v1"
      optional :devaddr_range, :message, 2, "helium.iot_config.devaddr_range_v1"
      optional :timestamp, :uint64, 3
      optional :signature, :bytes, 4
    end
    add_message "helium.iot_config.route_devaddr_ranges_res_v1" do
    end
    add_message "helium.iot_config.route_stream_req_v1" do
      optional :timestamp, :uint64, 1
      optional :signature, :bytes, 2
    end
    add_message "helium.iot_config.route_stream_res_v1" do
      optional :action, :enum, 1, "helium.iot_config.action_v1"
      oneof :data do
        optional :route, :message, 2, "helium.iot_config.route_v1"
        optional :eui_pair, :message, 3, "helium.iot_config.eui_pair_v1"
        optional :devaddr_range, :message, 4, "helium.iot_config.devaddr_range_v1"
      end
    end
    add_message "helium.iot_config.session_key_filter_v1" do
      optional :oui, :uint64, 1
      optional :devaddr, :uint32, 2
      optional :session_key, :string, 3
    end
    add_message "helium.iot_config.session_key_filter_list_req_v1" do
      optional :oui, :uint64, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.session_key_filter_get_req_v1" do
      optional :oui, :uint64, 1
      optional :devaddr, :uint32, 2
      optional :timestamp, :uint64, 3
      optional :signature, :bytes, 4
    end
    add_message "helium.iot_config.session_key_filter_update_req_v1" do
      optional :action, :enum, 1, "helium.iot_config.action_v1"
      optional :filter, :message, 2, "helium.iot_config.session_key_filter_v1"
      optional :timestamp, :uint64, 3
      optional :signature, :bytes, 4
    end
    add_message "helium.iot_config.session_key_filter_update_res_v1" do
    end
    add_message "helium.iot_config.session_key_filter_stream_req_v1" do
      optional :timestamp, :uint64, 1
      optional :signature, :bytes, 2
    end
    add_message "helium.iot_config.session_key_filter_stream_res_v1" do
      optional :action, :enum, 1, "helium.iot_config.action_v1"
      optional :filter, :message, 2, "helium.iot_config.session_key_filter_v1"
    end
    add_message "helium.iot_config.gateway_region_params_req_v1" do
      optional :region, :enum, 1, "helium.region"
      optional :address, :bytes, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.iot_config.gateway_region_params_res_v1" do
      optional :region, :enum, 1, "helium.region"
      optional :params, :message, 2, "helium.blockchain_region_params_v1"
      optional :gain, :uint64, 3
      optional :signature, :bytes, 4
    end
    add_message "helium.iot_config.gateway_location_req_v1" do
      optional :gateway, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "helium.iot_config.gateway_location_res_v1" do
      optional :location, :string, 1
    end
    add_message "helium.iot_config.admin_load_region_req_v1" do
      optional :region, :enum, 1, "helium.region"
      optional :params, :message, 2, "helium.blockchain_region_params_v1"
      optional :hex_indexes, :bytes, 3
      optional :signature, :bytes, 4
    end
    add_message "helium.iot_config.admin_load_region_res_v1" do
    end
    add_message "helium.iot_config.admin_add_key_req_v1" do
      optional :pubkey, :bytes, 1
      optional :key_type, :enum, 2, "helium.iot_config.admin_add_key_req_v1.key_type_v1"
      optional :signature, :bytes, 3
    end
    add_enum "helium.iot_config.admin_add_key_req_v1.key_type_v1" do
      value :administrator, 0
      value :packet_router, 1
    end
    add_message "helium.iot_config.admin_remove_key_req_v1" do
      optional :pubkey, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "helium.iot_config.admin_key_res_v1" do
    end
    add_enum "helium.iot_config.action_v1" do
      value :add, 0
      value :remove, 1
    end
  end
end

module Helium
  module IotConfig
    Org_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_v1").msgclass
    Devaddr_range_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.devaddr_range_v1").msgclass
    Devaddr_constraint_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.devaddr_constraint_v1").msgclass
    Eui_pair_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.eui_pair_v1").msgclass
    Protocol_packet_router_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.protocol_packet_router_v1").msgclass
    Protocol_gwmp_mapping_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.protocol_gwmp_mapping_v1").msgclass
    Protocol_gwmp_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.protocol_gwmp_v1").msgclass
    Protocol_http_roaming_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.protocol_http_roaming_v1").msgclass
    Protocol_http_roaming_v1::Flow_type_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.protocol_http_roaming_v1.flow_type_v1").enummodule
    Server_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.server_v1").msgclass
    Route_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_v1").msgclass
    Org_list_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_list_req_v1").msgclass
    Org_list_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_list_res_v1").msgclass
    Org_get_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_get_req_v1").msgclass
    Org_create_helium_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_create_helium_req_v1").msgclass
    Org_create_roamer_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_create_roamer_req_v1").msgclass
    Org_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_res_v1").msgclass
    Org_disable_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_disable_req_v1").msgclass
    Org_disable_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_disable_res_v1").msgclass
    Org_enable_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_enable_req_v1").msgclass
    Org_enable_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.org_enable_res_v1").msgclass
    Route_list_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_list_req_v1").msgclass
    Route_list_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_list_res_v1").msgclass
    Route_get_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_get_req_v1").msgclass
    Route_create_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_create_req_v1").msgclass
    Route_update_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_update_req_v1").msgclass
    Route_delete_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_delete_req_v1").msgclass
    Route_get_euis_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_get_euis_req_v1").msgclass
    Route_update_euis_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_update_euis_req_v1").msgclass
    Route_euis_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_euis_res_v1").msgclass
    Route_get_devaddr_ranges_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_get_devaddr_ranges_req_v1").msgclass
    Route_update_devaddr_ranges_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_update_devaddr_ranges_req_v1").msgclass
    Route_devaddr_ranges_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_devaddr_ranges_res_v1").msgclass
    Route_stream_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_stream_req_v1").msgclass
    Route_stream_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.route_stream_res_v1").msgclass
    Session_key_filter_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.session_key_filter_v1").msgclass
    Session_key_filter_list_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.session_key_filter_list_req_v1").msgclass
    Session_key_filter_get_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.session_key_filter_get_req_v1").msgclass
    Session_key_filter_update_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.session_key_filter_update_req_v1").msgclass
    Session_key_filter_update_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.session_key_filter_update_res_v1").msgclass
    Session_key_filter_stream_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.session_key_filter_stream_req_v1").msgclass
    Session_key_filter_stream_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.session_key_filter_stream_res_v1").msgclass
    Gateway_region_params_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.gateway_region_params_req_v1").msgclass
    Gateway_region_params_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.gateway_region_params_res_v1").msgclass
    Gateway_location_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.gateway_location_req_v1").msgclass
    Gateway_location_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.gateway_location_res_v1").msgclass
    Admin_load_region_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.admin_load_region_req_v1").msgclass
    Admin_load_region_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.admin_load_region_res_v1").msgclass
    Admin_add_key_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.admin_add_key_req_v1").msgclass
    Admin_add_key_req_v1::Key_type_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.admin_add_key_req_v1.key_type_v1").enummodule
    Admin_remove_key_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.admin_remove_key_req_v1").msgclass
    Admin_key_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.admin_key_res_v1").msgclass
    Action_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.iot_config.action_v1").enummodule
  end
end
