# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/local.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/local.proto", :syntax => :proto3) do
    add_message "helium.local.pubkey_res" do
      optional :address, :bytes, 1
      optional :onboarding_address, :bytes, 2
    end
    add_message "helium.local.pubkey_req" do
    end
    add_message "helium.local.sign_req" do
      optional :data, :bytes, 1
    end
    add_message "helium.local.sign_res" do
      optional :signature, :bytes, 1
    end
    add_message "helium.local.ecdh_req" do
      optional :address, :bytes, 1
    end
    add_message "helium.local.ecdh_res" do
      optional :secret, :bytes, 1
    end
    add_message "helium.local.config_req" do
      repeated :keys, :string, 1
    end
    add_message "helium.local.config_res" do
      repeated :values, :message, 1, "helium.local.config_value"
    end
    add_message "helium.local.config_value" do
      optional :name, :string, 1
      optional :type, :string, 2
      optional :value, :bytes, 3
    end
    add_message "helium.local.keyed_uri" do
      optional :address, :bytes, 1
      optional :uri, :string, 2
    end
    add_message "helium.local.height_req" do
    end
    add_message "helium.local.height_res" do
      optional :height, :uint64, 1
      optional :block_age, :uint64, 2
      optional :gateway, :message, 3, "helium.local.keyed_uri"
      proto3_optional :gateway_version, :uint64, 4
    end
    add_message "helium.local.region_req" do
    end
    add_message "helium.local.region_res" do
      optional :region, :int32, 1
    end
    add_message "helium.local.add_gateway_req" do
      optional :owner, :bytes, 1
      optional :payer, :bytes, 2
      optional :staking_mode, :enum, 3, "helium.local.gateway_staking_mode"
    end
    add_message "helium.local.add_gateway_res" do
      optional :add_gateway_txn, :bytes, 1
    end
    add_enum "helium.local.gateway_staking_mode" do
      value :dataonly, 0
      value :full, 1
      value :light, 2
    end
  end
end

module Helium
  module Local
    Pubkey_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.pubkey_res").msgclass
    Pubkey_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.pubkey_req").msgclass
    Sign_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.sign_req").msgclass
    Sign_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.sign_res").msgclass
    Ecdh_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.ecdh_req").msgclass
    Ecdh_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.ecdh_res").msgclass
    Config_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.config_req").msgclass
    Config_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.config_res").msgclass
    Config_value = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.config_value").msgclass
    Keyed_uri = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.keyed_uri").msgclass
    Height_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.height_req").msgclass
    Height_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.height_res").msgclass
    Region_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.region_req").msgclass
    Region_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.region_res").msgclass
    Add_gateway_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.add_gateway_req").msgclass
    Add_gateway_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.add_gateway_res").msgclass
    Gateway_staking_mode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.gateway_staking_mode").enummodule
  end
end
