# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/local.proto

require 'google/protobuf'

require 'gateway_staking_mode_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/local.proto", :syntax => :proto3) do
    add_message "helium.local.pubkey_res" do
      optional :address, :bytes, 1
      optional :onboarding_address, :bytes, 2
    end
    add_message "helium.local.pubkey_req" do
    end
    add_message "helium.local.keyed_uri" do
      optional :address, :bytes, 1
      optional :uri, :string, 2
    end
    add_message "helium.local.region_req" do
    end
    add_message "helium.local.region_res" do
      optional :region, :int32, 1
    end
    add_message "helium.local.router_req" do
    end
    add_message "helium.local.router_res" do
      optional :uri, :string, 1
      optional :connected, :bool, 2
    end
    add_message "helium.local.add_gateway_req" do
      optional :owner, :bytes, 1
      optional :payer, :bytes, 2
      optional :staking_mode, :enum, 3, "helium.gateway_staking_mode"
    end
    add_message "helium.local.add_gateway_res" do
      optional :add_gateway_txn, :bytes, 1
    end
  end
end

module Helium
  module Local
    Pubkey_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.pubkey_res").msgclass
    Pubkey_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.pubkey_req").msgclass
    Keyed_uri = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.keyed_uri").msgclass
    Region_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.region_req").msgclass
    Region_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.region_res").msgclass
    Router_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.router_req").msgclass
    Router_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.router_res").msgclass
    Add_gateway_req = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.add_gateway_req").msgclass
    Add_gateway_res = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.local.add_gateway_res").msgclass
  end
end
