# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/mobile_config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/mobile_config.proto", :syntax => :proto3) do
    add_message "helium.mobile_config.hotspot_metadata" do
      optional :address, :bytes, 1
      optional :location, :string, 2
    end
    add_message "helium.mobile_config.hotspot_metadata_req_v1" do
      optional :address, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "helium.mobile_config.hotspot_metadata_res_v1" do
      optional :metadata, :message, 1, "helium.mobile_config.hotspot_metadata"
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.mobile_config.hotspot_metadata_stream_req_v1" do
      optional :batch_size, :uint32, 1
      optional :signature, :bytes, 2
    end
    add_message "helium.mobile_config.hotspot_metadata_stream_res_v1" do
      repeated :hotspots, :message, 1, "helium.mobile_config.hotspot_metadata"
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.mobile_config.router_get_req_v1" do
      optional :pubkey, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "helium.mobile_config.router_get_res_v1" do
      optional :pubkey, :bytes, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.mobile_config.router_list_req_v1" do
      optional :signature, :bytes, 1
    end
    add_message "helium.mobile_config.router_list_res_v1" do
      repeated :routers, :bytes, 1
      optional :timestamp, :uint64, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.mobile_config.admin_add_key_req_v1" do
      optional :pubkey, :bytes, 1
      optional :key_type, :enum, 2, "helium.mobile_config.admin_add_key_req_v1.key_type_v1"
      optional :signature, :bytes, 3
    end
    add_enum "helium.mobile_config.admin_add_key_req_v1.key_type_v1" do
      value :administrator, 0
      value :packet_router, 1
    end
    add_message "helium.mobile_config.admin_remove_key_req_v1" do
      optional :pubkey, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "helium.mobile_config.admin_key_res_v1" do
    end
  end
end

module Helium
  module MobileConfig
    Hotspot_metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.hotspot_metadata").msgclass
    Hotspot_metadata_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.hotspot_metadata_req_v1").msgclass
    Hotspot_metadata_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.hotspot_metadata_res_v1").msgclass
    Hotspot_metadata_stream_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.hotspot_metadata_stream_req_v1").msgclass
    Hotspot_metadata_stream_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.hotspot_metadata_stream_res_v1").msgclass
    Router_get_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.router_get_req_v1").msgclass
    Router_get_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.router_get_res_v1").msgclass
    Router_list_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.router_list_req_v1").msgclass
    Router_list_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.router_list_res_v1").msgclass
    Admin_add_key_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.admin_add_key_req_v1").msgclass
    Admin_add_key_req_v1::Key_type_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.admin_add_key_req_v1.key_type_v1").enummodule
    Admin_remove_key_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.admin_remove_key_req_v1").msgclass
    Admin_key_res_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.mobile_config.admin_key_res_v1").msgclass
  end
end
