# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/packet_router.proto

require 'google/protobuf'

require 'region_pb'
require 'data_rate_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/packet_router.proto", :syntax => :proto3) do
    add_message "helium.packet_router.packet_router_packet_report_v1" do
      optional :gateway_timestamp_ms, :uint64, 1
      optional :oui, :uint64, 2
      optional :net_id, :uint32, 3
      optional :rssi, :sint32, 4
      optional :frequency, :uint32, 5
      optional :snr, :float, 6
      optional :datarate, :enum, 7, "helium.data_rate"
      optional :region, :enum, 8, "helium.region"
      optional :gateway, :bytes, 9
      optional :payload_hash, :bytes, 10
      optional :payload_size, :uint32, 11
    end
    add_message "helium.packet_router.packet_router_packet_up_v1" do
      optional :payload, :bytes, 1
      optional :timestamp, :uint64, 2
      optional :rssi, :sint32, 3
      optional :frequency, :uint32, 4
      optional :datarate, :enum, 5, "helium.data_rate"
      optional :snr, :float, 6
      optional :region, :enum, 7, "helium.region"
      optional :hold_time, :uint64, 8
      optional :gateway, :bytes, 9
      optional :signature, :bytes, 10
    end
    add_message "helium.packet_router.packet_router_register_v1" do
      optional :timestamp, :uint64, 1
      optional :gateway, :bytes, 2
      optional :signature, :bytes, 3
    end
    add_message "helium.packet_router.envelope_up_v1" do
      oneof :data do
        optional :register, :message, 1, "helium.packet_router.packet_router_register_v1"
        optional :packet, :message, 2, "helium.packet_router.packet_router_packet_up_v1"
      end
    end
    add_message "helium.packet_router.window_v1" do
      optional :timestamp, :uint64, 1
      optional :frequency, :uint32, 2
      optional :datarate, :enum, 3, "helium.data_rate"
      optional :immediate, :bool, 4
    end
    add_message "helium.packet_router.packet_router_packet_down_v1" do
      optional :payload, :bytes, 1
      optional :rx1, :message, 2, "helium.packet_router.window_v1"
      optional :rx2, :message, 3, "helium.packet_router.window_v1"
    end
    add_message "helium.packet_router.envelope_down_v1" do
      oneof :data do
        optional :packet, :message, 1, "helium.packet_router.packet_router_packet_down_v1"
      end
    end
  end
end

module Helium
  module PacketRouter
    Packet_router_packet_report_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.packet_router.packet_router_packet_report_v1").msgclass
    Packet_router_packet_up_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.packet_router.packet_router_packet_up_v1").msgclass
    Packet_router_register_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.packet_router.packet_router_register_v1").msgclass
    Envelope_up_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.packet_router.envelope_up_v1").msgclass
    Window_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.packet_router.window_v1").msgclass
    Packet_router_packet_down_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.packet_router.packet_router_packet_down_v1").msgclass
    Envelope_down_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.packet_router.envelope_down_v1").msgclass
  end
end
