# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/poc_mobile.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/poc_mobile.proto", :syntax => :proto3) do
    add_message "helium.poc_mobile.speedtest_req_v1" do
      optional :pub_key, :bytes, 1
      optional :serial, :string, 2
      optional :timestamp, :uint64, 3
      optional :upload_speed, :uint64, 4
      optional :download_speed, :uint64, 5
      optional :latency, :uint32, 6
      optional :signature, :bytes, 7
    end
    add_message "helium.poc_mobile.speedtest_resp_v1" do
      optional :id, :string, 1
    end
    add_message "helium.poc_mobile.cell_heartbeat_req_v1" do
      optional :pub_key, :bytes, 1
      optional :hotspot_type, :string, 2
      optional :cell_id, :uint32, 3
      optional :timestamp, :uint64, 4
      optional :lat, :double, 5
      optional :lon, :double, 6
      optional :operation_mode, :bool, 7
      optional :cbsd_category, :string, 8
      optional :cbsd_id, :string, 9
      optional :signature, :bytes, 10
    end
    add_message "helium.poc_mobile.cell_heartbeat_resp_v1" do
      optional :id, :string, 1
    end
  end
end

module Helium
  module PocMobile
    Speedtest_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_mobile.speedtest_req_v1").msgclass
    Speedtest_resp_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_mobile.speedtest_resp_v1").msgclass
    Cell_heartbeat_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_mobile.cell_heartbeat_req_v1").msgclass
    Cell_heartbeat_resp_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_mobile.cell_heartbeat_resp_v1").msgclass
  end
end
