# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/poc_entropy.proto

require 'google/protobuf'

require 'entropy_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/poc_entropy.proto", :syntax => :proto3) do
    add_message "helium.poc_entropy.entropy_req_v1" do
    end
  end
end

module Helium
  module PocEntropy
    Entropy_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_entropy.entropy_req_v1").msgclass
  end
end
