# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/poc_lora.proto

require 'google/protobuf'

require 'data_rate_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/poc_lora.proto", :syntax => :proto3) do
    add_message "helium.poc_lora.lora_beacon_report_req_v1" do
      optional :pub_key, :bytes, 2
      optional :local_entropy, :bytes, 3
      optional :remote_entropy, :bytes, 4
      optional :data, :bytes, 5
      optional :frequency, :uint64, 6
      optional :channel, :int32, 7
      optional :datarate, :enum, 8, "helium.data_rate"
      optional :tx_power, :int32, 9
      optional :timestamp, :uint64, 10
      optional :signature, :bytes, 11
      optional :tmst, :uint32, 12
    end
    add_message "helium.poc_lora.lora_beacon_report_resp_v1" do
      optional :id, :string, 1
    end
    add_message "helium.poc_lora.lora_witness_report_req_v1" do
      optional :pub_key, :bytes, 2
      optional :data, :bytes, 3
      optional :timestamp, :uint64, 4
      optional :tmst, :uint32, 5
      optional :signal, :sint32, 6
      optional :snr, :int32, 7
      optional :frequency, :uint64, 8
      optional :datarate, :enum, 10, "helium.data_rate"
      optional :signature, :bytes, 11
    end
    add_message "helium.poc_lora.lora_witness_report_resp_v1" do
      optional :id, :string, 1
    end
    add_message "helium.poc_lora.lora_beacon_ingest_report_v1" do
      optional :received_timestamp, :uint64, 1
      optional :report, :message, 2, "helium.poc_lora.lora_beacon_report_req_v1"
    end
    add_message "helium.poc_lora.lora_witness_ingest_report_v1" do
      optional :received_timestamp, :uint64, 1
      optional :report, :message, 2, "helium.poc_lora.lora_witness_report_req_v1"
    end
    add_message "helium.poc_lora.lora_valid_beacon_report_v1" do
      optional :received_timestamp, :uint64, 1
      optional :location, :string, 2
      optional :hex_scale, :uint32, 3
      optional :report, :message, 4, "helium.poc_lora.lora_beacon_report_req_v1"
      optional :reward_unit, :uint32, 5
    end
    add_message "helium.poc_lora.lora_valid_witness_report_v1" do
      optional :received_timestamp, :uint64, 1
      optional :location, :string, 2
      optional :hex_scale, :uint32, 3
      optional :report, :message, 4, "helium.poc_lora.lora_witness_report_req_v1"
      optional :reward_unit, :uint32, 5
    end
    add_message "helium.poc_lora.lora_invalid_beacon_report_v1" do
      optional :received_timestamp, :uint64, 1
      optional :reason, :enum, 2, "helium.poc_lora.invalid_reason"
      optional :report, :message, 3, "helium.poc_lora.lora_beacon_report_req_v1"
    end
    add_message "helium.poc_lora.lora_invalid_witness_report_v1" do
      optional :received_timestamp, :uint64, 1
      optional :reason, :enum, 2, "helium.poc_lora.invalid_reason"
      optional :report, :message, 3, "helium.poc_lora.lora_witness_report_req_v1"
      optional :participant_side, :enum, 4, "helium.poc_lora.invalid_participant_side"
    end
    add_message "helium.poc_lora.lora_verified_witness_report_v1" do
      optional :received_timestamp, :uint64, 1
      optional :status, :enum, 2, "helium.poc_lora.verification_status"
      optional :report, :message, 3, "helium.poc_lora.lora_witness_report_req_v1"
      optional :location, :string, 4
      optional :hex_scale, :uint32, 5
      optional :reward_unit, :uint32, 6
      optional :invalid_reason, :enum, 7, "helium.poc_lora.invalid_reason"
      optional :participant_side, :enum, 8, "helium.poc_lora.invalid_participant_side"
    end
    add_message "helium.poc_lora.lora_poc_v1" do
      optional :poc_id, :bytes, 1
      optional :beacon_report, :message, 2, "helium.poc_lora.lora_valid_beacon_report_v1"
      repeated :selected_witnesses, :message, 3, "helium.poc_lora.lora_verified_witness_report_v1"
      repeated :unselected_witnesses, :message, 4, "helium.poc_lora.lora_verified_witness_report_v1"
    end
    add_message "helium.poc_lora.gateway_reward_share" do
      optional :hotspot_key, :bytes, 1
      optional :beacon_amount, :uint64, 2
      optional :witness_amount, :uint64, 3
      optional :start_period, :uint64, 4
      optional :end_period, :uint64, 5
    end
    add_enum "helium.poc_lora.verification_status" do
      value :valid, 0
      value :invalid, 1
    end
    add_enum "helium.poc_lora.invalid_participant_side" do
      value :side_none, 0
      value :beaconer, 2
      value :witness, 3
    end
    add_enum "helium.poc_lora.invalid_reason" do
      value :reason_none, 0
      value :bad_signature, 1
      value :not_asserted, 2
      value :entropy_expired, 3
      value :bad_entropy, 4
      value :invalid_capability, 5
      value :invalid_pubkey, 6
      value :irregular_interval, 7
      value :gateway_not_found, 8
      value :denied, 9
      value :invalid_packet, 10
      value :bad_rssi, 11
      value :invalid_region, 12
      value :max_distance_exceeded, 13
      value :invalid_frequency, 14
      value :self_witness, 15
      value :stale, 16
      value :scaling_factor_not_found, 17
      value :unknown_error, 18
      value :below_min_distance, 19
      value :duplicate, 20
    end
  end
end

module Helium
  module PocLora
    Lora_beacon_report_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_beacon_report_req_v1").msgclass
    Lora_beacon_report_resp_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_beacon_report_resp_v1").msgclass
    Lora_witness_report_req_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_witness_report_req_v1").msgclass
    Lora_witness_report_resp_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_witness_report_resp_v1").msgclass
    Lora_beacon_ingest_report_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_beacon_ingest_report_v1").msgclass
    Lora_witness_ingest_report_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_witness_ingest_report_v1").msgclass
    Lora_valid_beacon_report_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_valid_beacon_report_v1").msgclass
    Lora_valid_witness_report_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_valid_witness_report_v1").msgclass
    Lora_invalid_beacon_report_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_invalid_beacon_report_v1").msgclass
    Lora_invalid_witness_report_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_invalid_witness_report_v1").msgclass
    Lora_verified_witness_report_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_verified_witness_report_v1").msgclass
    Lora_poc_v1 = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.lora_poc_v1").msgclass
    Gateway_reward_share = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.gateway_reward_share").msgclass
    Verification_status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.verification_status").enummodule
    Invalid_participant_side = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.invalid_participant_side").enummodule
    Invalid_reason = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("helium.poc_lora.invalid_reason").enummodule
  end
end
