# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service/router.proto

require 'google/protobuf'

require 'blockchain_state_channel_v1_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("service/router.proto", :syntax => :proto3) do
  end
end

module Helium
end
